# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JTReader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JTReader


pod 'Alamofire', '~> 4.4.0'
pod 'Kingfisher', '~> 3.6.2'
pod 'SwiftyJSON'
pod 'SnapKit', '~> 3.2.0'
pod 'EDStarRating'
pod 'MJRefresh'
pod 'ZipArchive'
pod 'TMCache'
end
